# Generated by Django 3.1.4 on 2023-11-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodinamico',
            name='data',
            field=models.TextField(),
        ),
    ]
