# Generated by Django 3.1.4 on 2023-11-19 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentopublico',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipamentopublico',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geometria',
            name='area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geometria',
            name='centroide',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='equipamento_publico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipamentopublico'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='geometria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.geometria'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proprietario'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='rrr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rrr'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='data_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rrr',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rrr',
            name='data_termino',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rrr',
            name='descricao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rrr',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
