# Generated by Django 3.1.4 on 2023-11-06 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipamentoPublico',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Geometria',
            fields=[
                ('id_geom', models.AutoField(primary_key=True, serialize=False)),
                ('centroide', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id_proprietario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RRR',
            fields=[
                ('id_RRR', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id_imovel', models.AutoField(primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('equipamento_publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipamentopublico')),
                ('geometria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.geometria')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proprietario')),
                ('rrr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rrr')),
            ],
        ),
    ]
