# Generated by Django 3.1.4 on 2023-11-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231105_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosDinamicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
    ]
