# Generated by Django 3.1.4 on 2023-11-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dadosdinamicos_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosDinamicos',
        ),
    ]
