# Generated by Django 3.1.4 on 2023-11-12 15:07

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20231111_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelodinamico',
            name='user',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
            preserve_default=False,
        ),
    ]
