# Generated by Django 3.1.4 on 2023-11-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_modelodinamico_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelodinamico',
            name='user',
        ),
    ]
