# Generated by Django 3.1.4 on 2023-11-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231105_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposDinamicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos_dinamicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.modelodinamico')),
            ],
        ),
    ]
