# Generated by Django 3.1.4 on 2023-11-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_camposdinamicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camposdinamicos',
            old_name='campos_dinamicos',
            new_name='modelo_dinamico',
        ),
        migrations.AddField(
            model_name='camposdinamicos',
            name='nome_campo',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
