# Generated by Django 3.1.4 on 2023-11-05 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20231105_1717'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CamposDinamicos',
        ),
    ]
